### ISSUE TITLE
Message "Illegal instruction (core dumped)" 

### ISSUE THREAD

**Issue by strongheart1** [IntersectMBO/cardano-addresses#125]
I get the message 

> "Illegal instruction (core dumped)"

 on the following command:

` cat key_for_account_0_address_0.txt | ./cardano-address address payment --network-tag 0 > pay_to_account_0_address_0.txt`

other commands, are ok, e.g.:
`cat account_0_public_root_key.txt | ./cardano-address key child 0/0 > key_for_account_0_address_0.txt`

cardano-address version
3.3.0 @ 7e062438fae15cf1025ab780adbe6ed26ac3e6e6

**Comment by strongheart1** [comment]
additional info: 
The precompiled binary for Linux was used.
CPU:       Topology: Quad Core model: AMD Phenom II X4 850 bits: 64 type: MCP arch: K10 rev: 3 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 26488 

It works without errors with a different PC with CPU : Intel Core i7

**Comment by jonringer** [comment]
Generally this happens if something like `-march=native` gets passed on the build machine, and it will use cpu extensions which are available to that machine, but may not be available in something like a `AMD Phenom II`.

How did you acquire or build `./cardano-address`?

**Comment by strongheart1** [comment]
I used the precompiled binaries from the versions below:

[cardano-addresses-3.3.0-linux64.tar.gz](https://github.com/input-output-hk/cardano-addresses/releases/download/3.3.0/cardano-addresses-3.3.0-linux64.tar.gz)

[cardano-addresses-3.4.0-linux64.tar.gz](https://github.com/input-output-hk/cardano-addresses/releases/download/3.4.0/cardano-addresses-3.4.0-linux64.tar.gz)

**Comment by paweljakubas** [comment]
cannot replicate this with new releases.
