### ISSUE TITLE
How to get raw private key for python nacl from extended_key?

### ISSUE THREAD

**Issue by cscsabai** [IntersectMBO/cardano-addresses#133]
Hello! For python NaCl lib's Signing Key needs a 32 byte long private key. but when I get private key from Cardano-address I got an extended_key with 64 bytes long. Is there any way to get the raw private key from this exteneded_key,  or other way to get the raw private key from Cardano-address?
Thanks

**Comment by paweljakubas** [comment]
hi @cscsabai  we will add this functionality for private keys very soon

**Comment by paweljakubas** [comment]
https://github.com/input-output-hk/cardano-addresses/pull/134

**Comment by paweljakubas** [comment]
solved in https://github.com/IntersectMBO/cardano-addresses/pull/266
