### ISSUE TITLE
Generate normal (non-extended keys)

### ISSUE THREAD

**Issue by cscsabai** [IntersectMBO/cardano-addresses#142]
With the following command I can easily generate normal (non-extended) signing/verification keys:

#cardano-cli address key-gen --verification-key-file test.vkey --signing-key-file test.skey

The result signing file looks like:
{
“type”: “PaymentSigningKeyShelley_ed25519”,
“description”: “Payment Signing Key”,
“cborHex”: “58205603938b6f6fa9acd09b692126fxxxxxxxx865c81f7ca1ddcb40b5d41xxxxxx”
}

Verification key file also contains a non-extended public key.

So this is a simple signing/verification key, what I can use PyNaCl library without any problems.

How can I generate similar normal (non extended) signing/verifying keys with Cardano-addresses?

I cannot find any way to generate non-extended keys from menemonic/derivation.

**Comment by paweljakubas** [comment]
Hi @cscsabai 

Let's assume we have mnemonic
```
$ cat recovery-phrase.prv 
nothing heart matrix fly sleep slogan tomato pulse what roof rail since plastic false enlist
```

Construct root extended private key 
```
$ cardano-address key from-recovery-phrase Shelley < recovery-phrase.prv > root.xprv
root_xsk1apjwjs3ksgm5mnnk0cc5v5emgv0hmafmmy8tffay5s2ffk69830whwznr46672ruucdzwwtv9upv72e4ylrypyz5m6cyh0p00t7n3u3agt20lv32j4kxcqlkzu78nzjx0ysxxlc2ghfz9prxfmrds802xsuhh404~
```
Construct extended private key for account ix=0H, role=0 and address ix=0
```
$ cardano-address key child 1852H/1815H/0H/0/0 < root.xprv > key.xsk
addr_xsk1kzl5vgev0u843tfnxqcwg0lmaf7zhdhczddaqhas6dp6m6z98302e3avp8mhu94kxkpj2gss064f74km3rrptafh4fsztekz8k5c469shcvx35wrdmus3xemp984lcwhs0jdtl4pfcsrfspe00h9pej6rg8drvcv
```

Create signing key using cardano-cli
```
$ cardano-cli key convert-cardano-address-key --shelley-payment-key --signing-key-file key.xsk --out-file key.skey
{
    "type": "PaymentExtendedSigningKeyShelley_ed25519_bip32",
    "description": "",
    "cborHex": "5880b0bf46232c7f0f58ad333030e43ffbea7c2bb6f8135bd05fb0d343ade8453c5eacc7ac09f77e16b635832522107eaa9f56db88c615f537aa6025e6c23da98ae8fbbbf6410e24532f35e9279febb085d2cc05b3b2ada1df77ea1951eb694f3834b0be1868d1c36ef9089b3b094f5fe1d783e4d5fea14e2034c0397bee50e65a1a"
}
```

Create corresponding verification key using cardano-cli
```
$ cardano-cli key verification-key --signing-key-file key.skey --verification-key-file key.vkey
{
    "type": "PaymentExtendedVerificationKeyShelley_ed25519_bip32",
    "description": "",
    "cborHex": "5840fbbbf6410e24532f35e9279febb085d2cc05b3b2ada1df77ea1951eb694f3834b0be1868d1c36ef9089b3b094f5fe1d783e4d5fea14e2034c0397bee50e65a1a"
}
```

Create verification key hash using cardano-cli
```
$ cardano-cli address key-hash --payment-verification-key-file key.vkey > key.hash
0185545935760c5e370d01e6f4fedbb89b7fd79e115f2837cfab9ea8
```
Alternatively, we can create non-extended key 
```
$ cardano-address key public --without-chain-code < key.xsk > key.vk
addr_vk1lwalvsgwy3fj7d0fy707hvy96txqtvaj4ksa7al2r9g7k6208q6qmrv9k3
```

Also, take notice that signing key can be translated to cborhex:
```
$ cat key.xsk | bech32
b0bf46232c7f0f58ad333030e43ffbea7c2bb6f8135bd05fb0d343ade8453c5eacc7ac09f77e16b635832522107eaa9f56db88c615f537aa6025e6c23da98ae8b0be1868d1c36ef9089b3b094f5fe1d783e4d5fea14e2034c0397bee50e65a1a
(but should be prefixed wth '5880' to be the same)
```

Moreover, basing on key.vk one can get hash
```
$ cardano-cli address key-hash --payment-verification-key $(cat key.vk) > key1.hash
0185545935760c5e370d01e6f4fedbb89b7fd79e115f2837cfab9ea8
```

Within cardano-addresses one can get cborhex of verification key (with chain code)
```
$ cardano-address key public --with-chain-code < key.xsk | bech32
fbbbf6410e24532f35e9279febb085d2cc05b3b2ada1df77ea1951eb694f3834b0be1868d1c36ef9089b3b094f5fe1d783e4d5fea14e2034c0397bee50e65a1a
(but should be prefixed wth '5840' to be the same)
```

Finally, we can get compute hash (but here we need to use without chain code):
```
$ cardano-address key public --without-chain-code < key.xsk | cardano-address key hash | bech32
0185545935760c5e370d01e6f4fedbb89b7fd79e115f2837cfab9ea8
```

**Comment by paweljakubas** [comment]
btw. I created PR adding the above to the documentation -> https://github.com/input-output-hk/cardano-addresses/pull/143

**Comment by paweljakubas** [comment]
also `bech32` is binary from https://github.com/input-output-hk/bech32

**Comment by cscsabai** [comment]
Thanks for the explanation, but I still have a problem. In the latest step in your document:

```
Producing cborhash,
$ cardano-address key child 1852H/1815H/0H/0/0 --without-chain-code < root.xprv | bech32
 b0bf46232c7f0f58ad333030e43ffbea7c2bb6f8135bd05fb0d343ade8453c5eacc7ac09f77e16b635832522107eaa9f56db88c615f537aa6025e6c23da98ae8
 (just signing key)
```

So the result is NOT a signing key, this is an extended signing key, because it is 128 bytes long. The normal signing keys (generated with cardano-cli by default) is 64 bytes long, and this is the only way to sign transactions with PyNaCl library.

Is there any way to generate normal (non-extended) private key with cardano addresses?

**Comment by paweljakubas** [comment]
So below is signing key + chain code (64+32=96 bytes):
```
$ cardano-address key child 1852H/1815H/0H/0/0 --with-chain-code < root.xprv | bech32
b0bf46232c7f0f58ad333030e43ffbea7c2bb6f8135bd05fb0d343ade8453c5eacc7ac09f77e16b635832522107eaa9f56db88c615f537aa6025e6c23da98ae8b0be1868d1c36ef9089b3b094f5fe1d783e4d5fea14e2034c0397bee50e65a1a
``` 
And below it is just signing key (64 bytes): 
```
cardano-address key child 1852H/1815H/0H/0/0 --without-chain-code < root.xprv | bech32
b0bf46232c7f0f58ad333030e43ffbea7c2bb6f8135bd05fb0d343ade8453c5eacc7ac09f77e16b635832522107eaa9f56db88c615f537aa6025e6c23da98ae8
```
Please use this branch to have it : https://github.com/input-output-hk/cardano-addresses/pull/134
We are going to support extended, non-extended private keys (not so straightforward like for public keys).
It is not released though

**Comment by KtorZ** [comment]
> Is there any way to generate normal (non-extended) private key with cardano addresses?

No. Not at the moment. cardano-addresses is specifically designed to work with key derivation and extended keys.

**Comment by cscsabai** [comment]
> And below it is just signing key (64 bytes):

Sorry I totally confused the key length. So the normal signing key (I guess) should be 32 bytes long (64 bytes in hex encoded). If you check Cardano-cli key-gen, that also generates 32 bytes long normal secret keys (by default).

The reason why I need it: in my project we are develop an automated transaction signing service in python. We are using the PyNaCl library to sign the transactions. 

```
signature = SigningKey(sk, encoder=HexEncoder).sign(bytes.fromhex(hexbytes))
```

PyNaCl is only supports 32 bytes (128 bits) long normal signing keys. source: https://pynacl.readthedocs.io/en/latest/signing/#nacl.signing.SigningKey

With cardano-cli generated signing key, I can sign and submit Cardano transactions. 
Although I cannot sign transactions with Cardano addresses generated extended signing keys (64 bytes long). If I just try to use the first 32 bytes, I got the following error when try to submit tx:
ApplyTxError [LedgerFailure (UtxowFailure (InvalidWitnessesUTXOW [VKey (VerKeyEd25519DSIGN (PublicKey 

So somehow I need a find a way to generate normal (non-extended) 32 bytes long signatures + verification keys...
