### ISSUE TITLE
[Need Info] Create transaction by cardano-node using payment address generated by cardano-addresses

### ISSUE THREAD

**Issue by hhqwerty** [IntersectMBO/cardano-addresses#145]
Hi, 
I'm new in Cardano-addresses. I have a problem when try to make a transaction by using cardano-node  using sender address generated by cardano-addresses.
So what I did is :

1. generate a root private key (root.xsk) from recovery phrase.
2. generate a payment verification key (addr.xvk)
3.  generate a payment address from a payment key (**payment.addr)**
------------------------
And the when I tried to make a transaction using  that (**payment.addr)**, 
I don't know what signing key should I use to sign this transaction:
```
cardano-cli transaction sign         
--tx-body-file body.raw         
--testnet-magic 1097911063         
--signing-key-file what_key_should_I_use          
--out-file signFile.signed 

```
Please help me

**Comment by wchance** [comment]
I am having the same issue seems we are using the Verification Key and we need to generate a Secret Private Key.

**Comment by hhqwerty** [comment]
> I am having the same issue seems we are using the Verification Key and we need to generate a Secret Private Key. Did you find a solution?
@wchance yes. please refer to this link https://cardano.stackexchange.com/a/2514/2817

**Comment by stasha** [comment]
Link posted by @hhqwerty  helped me a lot.

Here is additional info that may help understand additional stuff a little bit further: 
https://github.com/input-output-hk/cardano-addresses/issues/171

**Comment by paweljakubas** [comment]
Explained in Readme under point **Correspondence between keys in cardano-addresses and cardano-cli**
Last entry in [command line](https://github.com/IntersectMBO/cardano-addresses?tab=readme-ov-file#command-line)
