### ISSUE TITLE
Verification and Signing Key

### ISSUE THREAD

**Issue by chainlabsio** [IntersectMBO/cardano-addresses#150]
# Child Private Key not working

I was able to follow these steps to create keys

./cardano-address recovery-phrase generate --size 15 > mnemonic.prv
./cardano-address key from-recovery-phrase Shelley < mnemonic.prv > root.prv
./cardano-address key child 1852H/1815H/0H/0/0 < root.prv > addr.prv
./cardano-address key public --with-chain-code < addr.prv > addr.pub
./cardano-address address payment --network-tag mainnet < addr.pub > addr.pay

We deposited test funds to addr.pay successfully and would like to move the funds with Exodus Wallet and using the private key.

But when I try to use the addr.prv in Exodus wallet to move the funds it does not accept the format as a private key.   

Currently, the addr.prv starts with addr_xsk1..... and not sure if this is the correct format to work with Exodus Wallet or I have a Verification Key and need a Signing Key.   

Any guidance would be appreciated.

**Comment by paweljakubas** [comment]
solved in https://github.com/IntersectMBO/cardano-addresses/pull/266
