### ISSUE TITLE
Support Aeson 2

### ISSUE THREAD

**Issue by kk-hainq** [IntersectMBO/cardano-addresses#174]
Many packages (`cardano-base`, `plutus`, `cardano-ledeger`, etc.) in the Cardano ecosystem have added Aeson 2 support to bump dependencies together. More and more are following and it would be nice for this repository to do so as well. At a glance that would help `cardano-wallet`, `plutus-apps`, etc. to bump dependencies with Aeson 2.

I could open a PR if accepted!

**Comment by paweljakubas** [comment]
we are supporting now Aeson 2
