### ISSUE TITLE
Failed to build cardano-addresses-3.7.0

### ISSUE THREAD

**Issue by mbos01** [IntersectMBO/cardano-addresses#201]
Just finished installing cnode 1.35.3 on a new server. Building process ends correctly except for cardano-addresses, which ends with the below error.

This was following the https://cardano-community.github.io/guild-operators procedure. The coincashew procedure does not seem to build this file. (is it really necessary??)

Any ideas? Cheers!

lib/Cardano/Address/Script.hs:740:41: error:
    • Couldn't match type ‘Text’ with ‘Json.Key’
      Expected type: [Json.Pair]
        Actual type: [(Text, Value)]
    • In the first argument of ‘object’, namely
        ‘(fmap toPair (Map.toList cosigners'))’
      In the second argument of ‘(.=)’, namely
        ‘object (fmap toPair (Map.toList cosigners'))’
      In the expression:
        "cosigners" .= object (fmap toPair (Map.toList cosigners'))
    |
740 |         object [ "cosigners" .= object (fmap toPair (Map.toList cosigners'))
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

lib/Cardano/Address/Script.hs:778:28: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HM.HashMap Text Value’
      Expected type: HM.HashMap Text Value
        Actual type: Json.Object
    • In the first argument of ‘HM.toList’, namely ‘o’
      In the expression: HM.toList o
      In the expression:
        case HM.toList o of
          [] -> fail "Cosigners object array should not be empty"
          cs -> for (reverse cs) $ \ (numTxt, str) -> do ...
    |
778 |             case HM.toList o of
    |                            ^
cabal: Failed to build cardano-addresses-3.7.0 (which is required by
exe:cardano-address from cardano-addresses-cli-3.7.0). See the build log above
for details.

**Comment by mbos01** [comment]
All prereqs are in place. Checked and double checked.

**Comment by paweljakubas** [comment]
hi @mbos01 cardano-node 1.35.3 uses newer version of hw-aeson than cardano-addresses 3.7.0. Please use https://github.com/input-output-hk/cardano-addresses/releases/tag/3.12.0 - it is compatible with this version of cardano-node

**Comment by mbos01** [comment]
Thanks! Appreciate it!

Unfortunately this also ends with an error: (not the same error but still ..)

Failed to build cardano-addresses-3.12.0.
Build log (
/home/c_user/.cabal/logs/ghc-8.10.7/cardano-addresses-3.12.0-f97a6a2e3b1d9b89d6f300fa7e86468547585c9310ed83f2c322ed99c68ffc6e.log
):
Configuring library for cardano-addresses-3.12.0..
Preprocessing library for cardano-addresses-3.12.0..
Building library for cardano-addresses-3.12.0..
[ 1 of 16] Compiling Cardano.Address.Compat ( lib/Cardano/Address/Compat.hs, dist/build/Cardano/Address/Compat.o, dist/build/Cardano/Address/Compat.dyn_o )
[ 2 of 16] Compiling Cardano.Address.Internal ( lib/Cardano/Address/Internal.hs, dist/build/Cardano/Address/Internal.o, dist/build/Cardano/Address/Internal.dyn_o )
[ 3 of 16] Compiling Cardano.Codec.Bech32.Prefixes ( lib/Cardano/Codec/Bech32/Prefixes.hs, dist/build/Cardano/Codec/Bech32/Prefixes.o, dist/build/Cardano/Codec/Bech32/Prefixes.dyn_o )
[ 4 of 16] Compiling Cardano.Codec.Cbor ( lib/Cardano/Codec/Cbor.hs, dist/build/Cardano/Codec/Cbor.o, dist/build/Cardano/Codec/Cbor.dyn_o )
[ 5 of 16] Compiling Cardano.Mnemonic ( lib/Cardano/Mnemonic.hs, dist/build/Cardano/Mnemonic.o, dist/build/Cardano/Mnemonic.dyn_o )
[ 6 of 16] Compiling Cardano.Address.Derivation ( lib/Cardano/Address/Derivation.hs, dist/build/Cardano/Address/Derivation.o, dist/build/Cardano/Address/Derivation.dyn_o )
[ 7 of 16] Compiling Codec.Binary.Encoding ( lib/Codec/Binary/Encoding.hs, dist/build/Codec/Binary/Encoding.o, dist/build/Codec/Binary/Encoding.dyn_o )
[ 8 of 16] Compiling Cardano.Address.Script ( lib/Cardano/Address/Script.hs, dist/build/Cardano/Address/Script.o, dist/build/Cardano/Address/Script.dyn_o )

lib/Cardano/Address/Script.hs:804:18: error:
    Not in scope: ‘JM.toList’
    Module ‘HaskellWorks.Data.Aeson.Compat.Map’ does not export ‘toList’.
    |
804 |             case JM.toList o of
    |                  ^^^^^^^^^
cabal: Failed to build cardano-addresses-3.12.0 (which is required by
exe:cardano-address from cardano-addresses-cli-3.12.0). See the build log
above for details.

**Comment by paweljakubas** [comment]
please use the following to make sure it works fine:
```
nix develop
cabal build all
```
